'blank_issues_enabled': false
'contact_links':
  - 'about': >
        Please Read Issue Area Rules before submitting an issue. 
        For Chinese User: 没看完Issue区版规前少特么瞎几把乱提Issue
    'name': 'Issue Area Rules'
    'url': 'https://github.com/Cats-Team/AdRules/wiki/Issue-Area-Rules'
  - 'about': >
        Only For Chinese User: 建议提Issue前先看完这个
    'name': '提问的智慧'
    'url': 'https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md'
